#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
# make deploy — one command, prod backend.
#
# Reads .env.prod and does everything:
#   1. generate tools/infra/prod.auto.tfvars  (from .env.prod infra keys)
#   2. terraform: bootstrap apply              (data bucket, AR repo, secrets)
#   3. push secret versions to Secret Manager  (from .env.prod secret keys)
#   4. zip + upload the ingest Cloud Function source
#   5. build + push the robotics-render image
#   6. terraform apply                         (full — wires everything)
#
# Terraform is the single source of truth for prod env vars. You never
# hand-edit cloud_run.tf / cloud_functions.tf / *.tfvars.
#
# Prereqs: gcloud (authenticated), terraform, python3. Run from any dir.
# ════════════════════════════════════════════════════════════════════
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root
ROOT="$(pwd)"
ENVF=".env.prod"

[ -f "$ENVF" ] || { echo "!! $ENVF missing — cp .env.prod.example $ENVF and fill in"; exit 1; }

# Load .env.prod into the environment.
set -a; # shellcheck disable=SC1090
source "$ENVF"; set +a

# ── Validate required keys ──────────────────────────────────────────
: "${GCP_PROJECT:?set GCP_PROJECT in .env.prod}"
: "${REGION:?set REGION in .env.prod}"
: "${SECTOR:?set SECTOR in .env.prod}"
: "${DATA_BUCKET:?set DATA_BUCKET in .env.prod}"
: "${CARDS_BUCKET:?set CARDS_BUCKET in .env.prod}"
: "${GEMINI_API_KEY:?set GEMINI_API_KEY in .env.prod}"

# Deploy must act as YOUR user account (the project Owner), not the local
# Firestore service account. The Makefile exports GOOGLE_APPLICATION_CREDENTIALS
# from .env (that SA key is for the local docker stack only) — Terraform would
# otherwise authenticate as that SA, which lacks project IAM-admin and cannot
# create the per-tool service-account role bindings. Unset it so Terraform
# falls back to your `gcloud auth application-default login` credentials.
unset GOOGLE_APPLICATION_CREDENTIALS

# Terraform authenticates with Application Default Credentials — a SEPARATE
# credential store from `gcloud auth login` (the CLI account). Verify ADC
# exists and is usable up front, before doing any work.
if ! gcloud auth application-default print-access-token >/dev/null 2>&1; then
  echo "!! Application Default Credentials are missing or expired."
  echo "   ADC is separate from 'gcloud auth login' — Terraform uses ADC."
  echo "   Fix (as the project Owner), then re-run make deploy:"
  echo "     gcloud auth application-default login"
  exit 1
fi
echo "Terraform authenticates via your Application Default Credentials."

# Image tag: prefer the current git short SHA so every code change redeploys.
# Outside git, fall back to a UTC timestamp — NEVER a fixed tag like
# "latest": the image reference string in Terraform wouldn't change, so
# terraform apply sees no diff and Cloud Run keeps running the old
# digest it pinned at the previous revision (a build alone rolls out
# nothing).
TAG="${IMAGE_TAG:-}"
if git -C "$ROOT" rev-parse --short HEAD >/dev/null 2>&1; then
  TAG="${TAG:-$(git -C "$ROOT" rev-parse --short HEAD)}"
fi
TAG="${TAG:-$(date -u +%Y%m%d-%H%M%S)}"
INGEST_OBJECT="function-sources/robotics-ingest-${TAG}.zip"
HANDLES_OBJECT="function-sources/handle-resolver-${TAG}.zip"
AR="${REGION}-docker.pkg.dev/${GCP_PROJECT}/robotics"

echo "Deploy → project=${GCP_PROJECT} region=${REGION} tag=${TAG}"

# ── 1. Generate Terraform vars from .env.prod ───────────────────────
echo "── 1/6  prod.auto.tfvars ─────────────────────────────────────"
cat > tools/infra/prod.auto.tfvars <<EOF
# GENERATED by make deploy from .env.prod — do not edit by hand.
project_id           = "${GCP_PROJECT}"
region               = "${REGION}"
sector               = "${SECTOR}"
data_bucket_name     = "${DATA_BUCKET}"
cards_bucket_name    = "${CARDS_BUCKET}"
ingest_schedule      = "${INGEST_SCHEDULE:-0 6 * * *}"
image_tag            = "${TAG}"
ingest_source_object = "${INGEST_OBJECT}"
handles_source_object = "${HANDLES_OBJECT}"
google_cse_id        = "${GOOGLE_CSE_ID:-}"
handle_search_delay_s = "${HANDLE_SEARCH_DELAY_S:-}"
handle_fetch_delay_s  = "${HANDLE_FETCH_DELAY_S:-}"
handle_direct_delay_s = "${HANDLE_DIRECT_DELAY_S:-}"
handle_cache_collection = "${HANDLE_CACHE_COLLECTION:-handle-cache}"
EOF
echo "   wrote tools/infra/prod.auto.tfvars"

# Terraform state bucket (the gcs backend in main.tf) — must exist before
# `terraform init`, and Terraform can't create its own backend. Bucket name
# is fixed in main.tf; create it idempotently here.
TFSTATE_BUCKET="robotics-tfstate"
if ! gcloud storage buckets describe "gs://${TFSTATE_BUCKET}" --project="$GCP_PROJECT" >/dev/null 2>&1; then
  echo "   creating Terraform state bucket gs://${TFSTATE_BUCKET}"
  gcloud storage buckets create "gs://${TFSTATE_BUCKET}" \
    --project="$GCP_PROJECT" --location=US --uniform-bucket-level-access
  gcloud storage buckets update "gs://${TFSTATE_BUCKET}" --versioning
fi

cd tools/infra
# -reconfigure: ignore any stale local backend state from a prior partial run.
terraform init -input=false -reconfigure

# ── 2. Bootstrap: create the bucket / AR repo / secret containers ───
# These must exist before steps 3-5 can upload into them. Additive and
# safe, so auto-approved; the full apply below is left interactive.
echo "── 2/6  terraform bootstrap (bucket, AR repo, secrets) ───────"
terraform apply -input=false -auto-approve \
  -target=google_storage_bucket.robotics_data \
  -target=google_artifact_registry_repository.robotics \
  -target=google_secret_manager_secret.gemini_api_key
cd "$ROOT"

# ── 3. Push secret values to Secret Manager ─────────────────────────
# Idempotent: skips a secret that already has a version so re-runs are fast.
# Set FORCE=1 to push a new version (e.g. after rotating a key in .env.prod).
echo "── 3/6  Secret Manager versions ──────────────────────────────"
add_secret_version() {
  if [ -z "${FORCE:-}" ] && \
     gcloud secrets versions list "$1" --project="$GCP_PROJECT" --limit=1 \
       --format='value(name)' 2>/dev/null | grep -q .; then
    echo "   $1 — version exists, skipping (FORCE=1 to push a new one)"
    return
  fi
  printf '%s' "$2" | gcloud secrets versions add "$1" \
    --project="$GCP_PROJECT" --data-file=- >/dev/null
  echo "   $1 ← new version"
}
add_secret_version GEMINI_API_KEY  "$GEMINI_API_KEY"
# Search keys are optional (handle resolution falls back to direct fetch
# without them) — but the secret resources always exist, and a Cloud
# Function can't mount a secret with zero versions. Push "" if unset
# (empty = disabled; handles.search_provider_from_env ignores blanks).
add_secret_version BRAVE_API_KEY      "${BRAVE_API_KEY:-}"
add_secret_version SERPER_API_KEY     "${SERPER_API_KEY:-}"
add_secret_version GOOGLE_CSE_API_KEY "${GOOGLE_CSE_API_KEY:-}"

# ── 4. Package + upload the ingest Cloud Function source ────────────
echo "── 4/6  ingest function source → gs://${DATA_BUCKET}/${INGEST_OBJECT}"
STAGE="$(mktemp -d)"
cp tools/robotics-ingest/main.py tools/robotics-ingest/requirements.txt "$STAGE/"
cp -r src "$STAGE/src"
cp -r config "$STAGE/config"
find "$STAGE" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
# Python's built-in zipfile — avoids depending on the `zip` CLI being installed.
( cd "$STAGE" && python3 -m zipfile -c source.zip main.py requirements.txt src config )
gcloud storage cp "$STAGE/source.zip" "gs://${DATA_BUCKET}/${INGEST_OBJECT}" --project="$GCP_PROJECT"
rm -rf "$STAGE"

# handle-resolver function source (same pattern; Firestore-cached in prod).
echo "──      handle-resolver source → gs://${DATA_BUCKET}/${HANDLES_OBJECT}"
STAGE="$(mktemp -d)"
cp tools/handle-resolver/main.py tools/handle-resolver/requirements.txt "$STAGE/"
cp -r src "$STAGE/src"
find "$STAGE" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
( cd "$STAGE" && python3 -m zipfile -c source.zip main.py requirements.txt src )
gcloud storage cp "$STAGE/source.zip" "gs://${DATA_BUCKET}/${HANDLES_OBJECT}" --project="$GCP_PROJECT"
rm -rf "$STAGE"

# ── 5. Build + push the render image ────────────────────────────────
# Skips the build when the tag already exists in Artifact Registry, so a
# re-run after a later-step failure doesn't rebuild for minutes.
# Set FORCE=1 to rebuild (needed when code changed but the tag didn't).
echo "── 5/6  build + push images (Cloud Build) ────────────────────"
for svc in robotics-render; do
  if [ -z "${FORCE:-}" ] && \
     gcloud artifacts docker images describe "${AR}/${svc}:${TAG}" \
       --project="$GCP_PROJECT" >/dev/null 2>&1; then
    echo "   ${svc}:${TAG} — image exists, skipping build (FORCE=1 to rebuild)"
    continue
  fi
  echo "   building ${svc}:${TAG}"
  gcloud builds submit "tools/${svc}" \
    --project="$GCP_PROJECT" --tag="${AR}/${svc}:${TAG}" --quiet
done

# ── 6. Full terraform apply (interactive — review the plan) ─────────
echo "── 6/6  terraform apply ──────────────────────────────────────"
cd tools/infra
terraform apply -input=false

echo ""
echo "Deployed. Verify:"
echo "  gcloud functions logs read robotics-ingest --region=${REGION} --limit=20"
echo "  Frontend (Firebase Hosting) is separate — run: make deploy-frontend"
