#!/usr/bin/env bash
# Deploy frontend/ → Firebase Hosting.
#
# The frontend is STATIC ASSETS ONLY (HTML/JS/CSS). In prod it reads
# catalysts + graph from Firestore (CKG-Robotics) and card PNGs from
# Firebase Storage — live, in the browser, via the Firebase Web SDK.
#
# Firebase requires firebase.json + the `public` dir to share a tree, so
# firebase.json lives at the REPO ROOT (public = frontend/). This script
# runs the firebase CLI from there. It also auto-creates .firebaserc and
# frontend/firebase-config.js — no Firebase Console copy-paste.
#
# Prereqs (one-time, on your machine):
#   - npm install -g firebase-tools
#   - firebase login          (or `make firebase-login` for a headless token)
#
# Usage:
#   ./deploy.sh                        # live deploy
#   DEPLOY_TARGET=preview ./deploy.sh  # 7-day disposable preview channel
set -euo pipefail

cd "$(dirname "$0")/../.."      # repo root — where firebase.json lives
CONFIG_JS="frontend/firebase-config.js"
DEPLOY_TARGET="${DEPLOY_TARGET:-live}"

command -v firebase >/dev/null 2>&1 || {
  echo "!! firebase CLI not found. Install + log in (one-time):"
  echo "     npm install -g firebase-tools"
  echo "     firebase login"
  exit 1
}

# ── Load .env.prod (project, sector, buckets) ───────────────────────
ENVF=".env.prod"
[ -f "$ENVF" ] || { echo "!! ${ENVF} missing — cp .env.prod.example .env.prod"; exit 1; }
set -a; # shellcheck disable=SC1090
source "$ENVF"; set +a
: "${GCP_PROJECT:?set GCP_PROJECT in .env.prod}"
: "${SECTOR:?set SECTOR in .env.prod}"
: "${CARDS_BUCKET:?set CARDS_BUCKET in .env.prod}"

# ── Firebase auth ───────────────────────────────────────────────────
# firebase-tools authenticates headlessly from a service-account key.
# `make firebase-sa` creates the key and records FIREBASE_DEPLOY_KEY here.
# A deprecated FIREBASE_TOKEN, if present, would override the key — drop it.
unset FIREBASE_TOKEN
if [ -n "${FIREBASE_DEPLOY_KEY:-}" ] && [ -f "${FIREBASE_DEPLOY_KEY}" ]; then
  export GOOGLE_APPLICATION_CREDENTIALS="$FIREBASE_DEPLOY_KEY"
  # A cached interactive `firebase login` (configstore) OUTRANKS the SA key —
  # and a stale/expired one fails the deploy. Clear it so firebase-tools
  # falls through to GOOGLE_APPLICATION_CREDENTIALS. Safe + idempotent: this
  # tool authenticates via the SA key regardless.
  firebase logout >/dev/null 2>&1 || true
  echo "Firebase auth: service-account key (${FIREBASE_DEPLOY_KEY})."
elif [ -n "${GOOGLE_APPLICATION_CREDENTIALS:-}" ] && [ -f "${GOOGLE_APPLICATION_CREDENTIALS}" ]; then
  echo "Firebase auth: GOOGLE_APPLICATION_CREDENTIALS from the environment."
else
  echo "!! No Firebase deploy credential. Create one (one-time):"
  echo "     make firebase-sa"
  exit 1
fi

# ── .firebaserc — which Firebase project to deploy to ───────────────
if [ ! -f .firebaserc ]; then
  cat > .firebaserc <<EOF
{
  "projects": {
    "default": "${GCP_PROJECT}"
  }
}
EOF
  echo "Created .firebaserc → project '${GCP_PROJECT}'"
fi

# ── frontend/firebase-config.js — the browser's Firestore/Storage wiring ──
# Generated from the project's Firebase Web app via the firebase CLI — no
# manual Console copy-paste. Delete the file to regenerate it.
if [ ! -f "$CONFIG_JS" ]; then
  echo "Generating ${CONFIG_JS} via the firebase CLI..."

  list_web_app_id() {
    firebase apps:list WEB --project "$GCP_PROJECT" --json 2>/dev/null \
      | python3 -c 'import json,sys
try: a = json.load(sys.stdin).get("result") or []
except Exception: a = []
print(a[0]["appId"] if a else "")' || true
  }

  appid="$(list_web_app_id)"
  if [ -z "$appid" ]; then
    echo "  no Firebase Web app registered — creating one"
    firebase apps:create WEB "Catalyst KG ${SECTOR}" --project "$GCP_PROJECT" >/dev/null
    appid="$(list_web_app_id)"
  fi
  [ -n "$appid" ] || { echo "!! could not find or create a Firebase Web app"; exit 1; }

  tmpcfg="$(mktemp)"
  if firebase apps:sdkconfig WEB "$appid" --project "$GCP_PROJECT" --json 2>/dev/null \
       | SECTOR="$SECTOR" CARDS_BUCKET="$CARDS_BUCKET" python3 -c '
import json, os, sys
cfg = json.load(sys.stdin)["result"]["sdkConfig"]
data = {
    "projectId":        cfg.get("projectId"),
    "apiKey":           cfg.get("apiKey"),
    "authDomain":       cfg.get("authDomain"),
    "appId":            cfg.get("appId"),
    "databaseId":       "(default)",
    "collection":       "CKG-" + os.environ["SECTOR"],
    "catalystsSubpath": "catalysts",
    "graphSubpath":     "graph",
    "sector":           os.environ["SECTOR"],
    "cardsBucket":      os.environ["CARDS_BUCKET"],
    "cardsPrefix":      "cards",
}
print("// Generated by make deploy-frontend — do not edit by hand.")
print("window.FIREBASE_CONFIG = " + json.dumps(data, indent=2) + ";")
' > "$tmpcfg" && [ -s "$tmpcfg" ]; then
    mv "$tmpcfg" "$CONFIG_JS"
    echo "  wrote ${CONFIG_JS} (Web app ${appid})"
  else
    rm -f "$tmpcfg"
    echo "!! failed to fetch the Web app SDK config"
    exit 1
  fi
fi

# ── Ensure the project is Firebase-enabled with a Hosting site ──────
# A plain GCP project must be registered with Firebase before Hosting
# works at all. Best-effort here — if it fails (permissions, API), do the
# one-time Console onboarding: console.firebase.google.com → Add project →
# pick the existing GCP project. All steps below are idempotent.
firebase projects:addfirebase "$GCP_PROJECT" >/dev/null 2>&1 || true

if ! firebase hosting:sites:list --project "$GCP_PROJECT" --json 2>/dev/null \
     | python3 -c 'import json,sys
try:
    r = json.load(sys.stdin).get("result")
    s = r.get("sites") if isinstance(r, dict) else (r if isinstance(r, list) else [])
except Exception:
    s = []
sys.exit(0 if s else 1)'; then
  echo "Creating Firebase Hosting site ${GCP_PROJECT}..."
  firebase hosting:sites:create "$GCP_PROJECT" --project "$GCP_PROJECT"
fi

# ── Public preview — newest few real cards baked into the bundle ────
# The landing page shows these to visitors who haven't signed in yet (a
# peek at real data behind the sign-in modal). The full catalyst set + the
# graph stay auth-gated in Firestore; preview.json is a static public subset.
# Non-fatal: if it fails, the page falls back to its built-in sample cards.
echo "Building frontend/preview.json (public teaser cards)..."
if ! python3 tools/frontend-deploy/build_preview.py "$GCP_PROJECT" "$SECTOR" frontend/preview.json; then
  echo "  !! preview build failed — landing page will use built-in samples"
  rm -f frontend/preview.json
fi

# ── Deploy the static bundle ────────────────────────────────────────
# --non-interactive: fail with a clear error instead of prompting (a prompt
# in a Makefile recipe is unanswerable noise). Hosting only — Storage rules
# are a separate step (see the closing message).
if [ "$DEPLOY_TARGET" = "live" ]; then
  firebase deploy --only hosting --project "$GCP_PROJECT" --non-interactive
else
  firebase hosting:channel:deploy "$DEPLOY_TARGET" --expires 7d --project "$GCP_PROJECT" --non-interactive
fi

echo ""
echo "Frontend deployed. It requires sign-in, then reads catalysts live from"
echo "Firestore (CKG-${SECTOR})."
echo ""
echo "Make sure these are done (one-time, see DEPLOYMENT.md):"
echo "  - Console → Authentication: enable sign-in providers."
echo "      Modal renders: Google, Email/Password, Phone."
echo "      X / GitHub are deferred (need an OAuth app + a SOCIAL[] edit)."
echo "  - Firestore Security Rules deployed, from the repo root:"
echo "      firebase deploy --only firestore --project ${GCP_PROJECT}"
echo ""
echo "Card PNGs (social posts) live in the private ${CARDS_BUCKET} bucket;"
echo "the web frontend renders HTML cards and does not need them."
